#!/bin/sh

ROOT="$( cd "$( dirname "$0" )" && pwd -P)"

cat > ~/.bashrc <<'EOF'
# do not edit this file. put files in the dir below.
for FN in $HOME/.local/bashrc.d/*.sh ; do
    source "$FN"
done
EOF

cat > ~/.zshrc <<'EOF'
# do not edit this file. put files in the dir below.
for FN in $HOME/.local/zshrc.d/*.sh ; do
    source "$FN"
done
EOF

cat > ~/.ssh/config <<'EOF'
Host *
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFIle ~/.ssh/id_rsa
EOF

cat > ~/.gitignore_global <<'EOF'
*~
.DS_Store
EOF

cat > ~/.gitconfig <<EOF
[user]
	name = cmilhench
	email = cmilhench@gmail.com

[alias]
	s = status -sb
	sg = log --oneline --graph --decorate --all

[core]
	editor = vim
	excludesfile = $HOME/.gitignore_global

[filter "lfs"]
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f

[url "git@github.com:"]
	insteadOf = https://github.com/
EOF

cat "$ROOT"/vimrc > ~/.vimrc

# install brew packages
if command -v brew >/dev/null 2>&1 ; then
    brew install bash-completion
    brew install entr
    brew install git
    brew install tree
    brew install jq
fi

